In [6]:
import numpy as np
import pandas as pd

import matplotlib.pyplot as plt
import seaborn as sns
color = sns.color_palette()
sns.set_style('darkgrid')  # 设置背景主题

import warnings
def ignore_warn(*args, **kwargs):
    pass
warnings.warn = ignore_warn  # 忽略各种warn信息

from scipy import stats
from scipy.stats import norm, skew
%matplotlib inline

In [7]:
data_train = pd.read_csv('./data/train.csv')
data_test = pd.read_csv('./data/test.csv')
combine = [data_train, data_test]
data_train.head()

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
0,1,60,RL,65.0,8450,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2008,WD,Normal,208500
1,2,20,RL,80.0,9600,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,5,2007,WD,Normal,181500
2,3,60,RL,68.0,11250,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,9,2008,WD,Normal,223500
3,4,70,RL,60.0,9550,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2006,WD,Abnorml,140000
4,5,60,RL,84.0,14260,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,12,2008,WD,Normal,250000

In [8]:
data_test.head()

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,ScreenPorch,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition
0,1461,20,RH,80.0,11622,Pave,NaN,Reg,Lvl,AllPub,...,120,0,NaN,MnPrv,NaN,0,6,2010,WD,Normal
1,1462,20,RL,81.0,14267,Pave,NaN,IR1,Lvl,AllPub,...,0,0,NaN,NaN,Gar2,12500,6,2010,WD,Normal
2,1463,60,RL,74.0,13830,Pave,NaN,IR1,Lvl,AllPub,...,0,0,NaN,MnPrv,NaN,0,3,2010,WD,Normal
3,1464,60,RL,78.0,9978,Pave,NaN,IR1,Lvl,AllPub,...,0,0,NaN,NaN,NaN,0,6,2010,WD,Normal
4,1465,120,RL,43.0,5005,Pave,NaN,IR1,HLS,AllPub,...,144,0,NaN,NaN,NaN,0,1,2010,WD,Normal

In [9]:
# 删除Id
trainId = data_train['Id']
testId = data_test['Id']
data_train.drop(['Id'], axis=1, inplace=True)
data_test.drop(['Id'], axis=1, inplace=True)

In [11]:
# 删除异常点
data_train = data_train.drop(data_train[(data_train['GrLivArea'] > 4000) & (data_train['SalePrice'] < 300000)].index)

In [13]:
ntrain = data_train.shape[0]
trainY = data_train.SalePrice.values
dataSet = pd.concat([data_train, data_test], axis=0)
dataSet.drop(['SalePrice'], axis=1, inplace=True)
dataSet.shape

(2917, 79)

In [46]:
total = dataSet.isnull().sum().sort_values(ascending=False)
total.head(40)

PoolQC          2908
MiscFeature     2812
Alley           2719
Fence           2346
FireplaceQu     1420
GarageCond       159
GarageFinish     159
GarageQual       159
GarageType       157
BsmtCond          82
BsmtExposure      82
BsmtQual          81
BsmtFinType2      80
BsmtFinType1      79
MasVnrType        24
MasVnrArea        23
MSZoning           4
Utilities          2
BsmtFullBath       2
BsmtHalfBath       2
Functional         2
GarageArea         1
KitchenQual        1
Exterior2nd        1
Exterior1st        1
BsmtFinSF1         1
Electrical         1
BsmtFinSF2         1
GarageCars         1
BsmtUnfSF          1
SaleType           1
TotalBsmtSF        1
Fireplaces         0
3SsnPorch          0
FullBath           0
2ndFlrSF           0
Foundation         0
ExterCond          0
BedroomAbvGr       0
ExterQual          0
dtype: int64

In [24]:
dataSet['GarageYrBlt'] = dataSet['GarageYrBlt'].fillna(method='ffill')
dataSet['GarageYrBlt'].isnull().sum()

0

In [26]:
garage = list(dataSet['GarageYrBlt'])
built = list(dataSet['YearBuilt'])
error = 0
for i in range(len(built)):
    if built[i] != garage[i]:
        error +=1
        
print(error / len(built))

0.2379156667809393

In [32]:
dataSet['LotFrontage'] = dataSet.groupby('Neighborhood')['LotFrontage'].transform(lambda x: x.fillna(x.median()))

In [43]:
data_test['Utilities'].value_counts()

AllPub    1457
Name: Utilities, dtype: int64

In [48]:
dataSet.dtypes

1stFlrSF           int64
2ndFlrSF           int64
3SsnPorch          int64
Alley             object
BedroomAbvGr       int64
BldgType          object
BsmtCond          object
BsmtExposure      object
BsmtFinSF1       float64
BsmtFinSF2       float64
BsmtFinType1      object
BsmtFinType2      object
BsmtFullBath     float64
BsmtHalfBath     float64
BsmtQual          object
BsmtUnfSF        float64
CentralAir        object
Condition1        object
Condition2        object
Electrical        object
EnclosedPorch      int64
ExterCond         object
ExterQual         object
Exterior1st       object
Exterior2nd       object
Fence             object
FireplaceQu       object
Fireplaces         int64
Foundation        object
FullBath           int64
                  ...
LotFrontage      float64
LotShape          object
LowQualFinSF       int64
MSSubClass         int64
MSZoning          object
MasVnrArea       float64
MasVnrType        object
MiscFeature       object
MiscVal            int64
MoSold             int64
Neighborhood      object
OpenPorchSF        int64
OverallCond        int64
OverallQual        int64
PavedDrive        object
PoolArea           int64
PoolQC            object
RoofMatl          object
RoofStyle         object
SaleCondition     object
SaleType          object
ScreenPorch        int64
Street            object
TotRmsAbvGrd       int64
TotalBsmtSF      float64
Utilities         object
WoodDeckSF         int64
YearBuilt          int64
YearRemodAdd       int64
YrSold             int64
Length: 79, dtype: object